"""Inject the measured detection-quality table into the README.

The numbers in the README are the numbers the harness produced, because they are
written by the harness. Hand-typed metrics drift the moment a rule changes, and
a portfolio repo quoting stale figures is worse than one quoting none.
"""
from __future__ import annotations

import json
from typing import Any

from detkit.paths import DETECTIONS, EVAL_RESULTS, README, REPO
from detkit.rules import load_corpus

START = "<!-- detkit:eval-table:start -->"
END = "<!-- detkit:eval-table:end -->"


class ReadmeError(Exception):
    """The README could not be updated."""


def _fmt(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.2f}"


def build_table() -> str:
    if not EVAL_RESULTS.is_file():
        raise ReadmeError(f"{EVAL_RESULTS} missing — run `detkit eval` first")
    results: dict[str, Any] = json.loads(EVAL_RESULTS.read_text(encoding="utf-8"))["rules"]
    levels = {rule.stem: str(rule.doc.get("level", "")) for rule in load_corpus(DETECTIONS)}

    rows = sorted(
        results.items(),
        key=lambda item: (
            item[1]["fp_rate"] if item[1]["fp_rate"] is not None else 1.0,
            -(item[1]["precision"] or 0.0),
        ),
    )

    total_cases = sum(r["tp"] + r["fp"] + r["fn"] + r["tn"] for _, r in rows)
    lines = [
        START,
        "",
        f"{len(rows)} rules, {total_cases} labelled events. Generated by "
        f"`detkit eval`; CI fails if this table drifts from the corpus.",
        "",
        "| rule | level | precision | recall | FP rate | bar it must clear |",
        "|---|---|---:|---:|---:|---|",
    ]
    for stem, metrics in rows:
        thresholds = metrics.get("thresholds", {})
        bar = (
            f"p≥{thresholds.get('min_precision', 0.9):.2f}, "
            f"r≥{thresholds.get('min_recall', 1.0):.2f}, "
            f"fp≤{thresholds.get('max_fp_rate', 0.1):.2f}"
        )
        fp_rate = metrics["fp_rate"]
        alerts_on_everything = fp_rate is not None and fp_rate >= 1.0
        fp_cell = f"**{_fmt(fp_rate)}**" if alerts_on_everything else _fmt(fp_rate)
        lines.append(
            f"| `{stem}` | {levels.get(stem, '?')} | {_fmt(metrics['precision'])} | "
            f"{_fmt(metrics['recall'])} | {fp_cell} | {bar} |"
        )
    lines += ["", END]
    return "\n".join(lines)


def run() -> int:
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise ReadmeError(f"README.md is missing the {START} / {END} markers")

    head, _, rest = text.partition(START)
    _, _, tail = rest.partition(END)
    README.write_text(head + build_table() + tail, encoding="utf-8")
    print(f"Wrote the eval table into {README.relative_to(REPO)}")
    return 0
